# Generated by Django 3.1.5 on 2021-01-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("requests", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="activationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "submitted"),
                    ("approved", "approved"),
                    ("canceled", "canceled"),
                    ("rejected", "rejected"),
                ],
                default="submitted",
                max_length=9,
                verbose_name="status",
            ),
        )
    ]
